/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SkSocialLink {
    'icon': string;
    'iconAddBackground': boolean;
    'iconViewbox': string;
    'text': string;
    'url': string;
  }
  interface SkTag {
    'text': string;
  }
  interface SkTagList {
    'items': Array<string>;
  }
  interface SkTypography {}
}

declare global {


  interface HTMLSkSocialLinkElement extends Components.SkSocialLink, HTMLStencilElement {}
  var HTMLSkSocialLinkElement: {
    prototype: HTMLSkSocialLinkElement;
    new (): HTMLSkSocialLinkElement;
  };

  interface HTMLSkTagElement extends Components.SkTag, HTMLStencilElement {}
  var HTMLSkTagElement: {
    prototype: HTMLSkTagElement;
    new (): HTMLSkTagElement;
  };

  interface HTMLSkTagListElement extends Components.SkTagList, HTMLStencilElement {}
  var HTMLSkTagListElement: {
    prototype: HTMLSkTagListElement;
    new (): HTMLSkTagListElement;
  };

  interface HTMLSkTypographyElement extends Components.SkTypography, HTMLStencilElement {}
  var HTMLSkTypographyElement: {
    prototype: HTMLSkTypographyElement;
    new (): HTMLSkTypographyElement;
  };
  interface HTMLElementTagNameMap {
    'sk-social-link': HTMLSkSocialLinkElement;
    'sk-tag': HTMLSkTagElement;
    'sk-tag-list': HTMLSkTagListElement;
    'sk-typography': HTMLSkTypographyElement;
  }
}

declare namespace LocalJSX {
  interface SkSocialLink {
    'icon'?: string;
    'iconAddBackground'?: boolean;
    'iconViewbox'?: string;
    'text'?: string;
    'url'?: string;
  }
  interface SkTag {
    'text'?: string;
  }
  interface SkTagList {
    'items'?: Array<string>;
  }
  interface SkTypography {}

  interface IntrinsicElements {
    'sk-social-link': SkSocialLink;
    'sk-tag': SkTag;
    'sk-tag-list': SkTagList;
    'sk-typography': SkTypography;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'sk-social-link': LocalJSX.SkSocialLink & JSXBase.HTMLAttributes<HTMLSkSocialLinkElement>;
      'sk-tag': LocalJSX.SkTag & JSXBase.HTMLAttributes<HTMLSkTagElement>;
      'sk-tag-list': LocalJSX.SkTagList & JSXBase.HTMLAttributes<HTMLSkTagListElement>;
      'sk-typography': LocalJSX.SkTypography & JSXBase.HTMLAttributes<HTMLSkTypographyElement>;
    }
  }
}


