/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SkTag {
    'text': string;
  }
  interface SkTagList {
    'items': Array<string>;
  }
}

declare global {


  interface HTMLSkTagElement extends Components.SkTag, HTMLStencilElement {}
  var HTMLSkTagElement: {
    prototype: HTMLSkTagElement;
    new (): HTMLSkTagElement;
  };

  interface HTMLSkTagListElement extends Components.SkTagList, HTMLStencilElement {}
  var HTMLSkTagListElement: {
    prototype: HTMLSkTagListElement;
    new (): HTMLSkTagListElement;
  };
  interface HTMLElementTagNameMap {
    'sk-tag': HTMLSkTagElement;
    'sk-tag-list': HTMLSkTagListElement;
  }
}

declare namespace LocalJSX {
  interface SkTag {
    'text'?: string;
  }
  interface SkTagList {
    'items'?: Array<string>;
  }

  interface IntrinsicElements {
    'sk-tag': SkTag;
    'sk-tag-list': SkTagList;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'sk-tag': LocalJSX.SkTag & JSXBase.HTMLAttributes<HTMLSkTagElement>;
      'sk-tag-list': LocalJSX.SkTagList & JSXBase.HTMLAttributes<HTMLSkTagListElement>;
    }
  }
}


