name: Push master to Chromatic

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
        registry-url: 'https://npm.pkg.github.com'
    - run:
        cd stencil/
        npm ci
        npm run build
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        cd storybook/
        npm ci
        npm run chromatic
