name: Push master to Chromatic

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: 'https://npm.pkg.github.com'
    - run: npm ci
      working-directory: core
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: npm run build
      working-directory: core
    - run: npm ci
      working-directory: documentation
    - run: npm run chromatic
      working-directory: documentation
