name: Push latest master to Chromatic

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        ls -la
        cd stencil/
        ls -la
        npm ci
        npm run build
        cd ../storybook
        ls -la
        npm ci
        npm run chromatic
